In [9]:
import pandas as pd
import datetime as dt

In [10]:
pd.set_option('display.max_rows',None)

In [11]:
accounts=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Other/Finance Project/Cleaned CSVs/accounts_transactions_joined_cleaned.csv')
accounts.head(50)

,transaction_id,transaction_date,account_type,branch_city,branch_state,amount,transaction_type,category,merchant,payment_method,status
0,106499.0,2025-12-01,Money Market,Albany,New York,2282.09,Payment,Transportation,EZ-Pass,Wire Transfer,Completed
1,101635.0,2025-02-27,Savings,Philadelphia,Pennsylvania,431.86,Transfer,Transportation,Lyft,NaN,Pending
2,102938.0,2024-05-31,Checking,Stamford,Connecticut,277.69,Transfer,Shopping,Amazon,Cash,Completed
3,110478.0,2022-07-20,Credit Card,New York,New York,2999.37,Transfer,Shopping,Target,Cash,Completed
4,100906.0,2023-11-24,Savings,Hartford,Connecticut,1087.05,Withdrawal,Fees,Late Fee,Cash,Completed
5,104027.0,2025-09-03,Money Market,Jersey City,New Jersey,102.75,Withdrawal,Utilities,PSEG,Debit Card,Pending
6,105516.0,2025-05-17,Credit Card,New York,New York,1605.73,Fee,Rent,Rent Payment,Cash,Completed
7,108794.0,2025-09-06,Credit Card,Newark,New Jersey,486.99,Deposit,Fees,Late Fee,Debit Card,Completed
8,107911.0,2022-05-06,Checking,Philadelphia,Pennsylvania,1844.79,Payment,Fees,Late Fee,Cash,Completed
9,105279.0,2025-04-27,Money Market,Hicksville,New York,2495.04,Withdrawal,Utilities,National Grid,Cash,Completed
10,108373.0,2025-11-07,Credit Card,Boston,Massachusetts,3060.68,Deposit,Groceries,Stop & Shop,Wire Transfer,Completed
11,102618.0,2024-02-24,Credit Card,Trenton,New Jersey,2562.89,Transfer,Entertainment,Hulu,Cash,Completed
12,105580.0,2024-08-18,Checking,Albany,New York,1344.25,Withdrawal,Transportation,EZ-Pass,Check,Completed
13,101092.0,2023-06-19,Savings,Trenton,New Jersey,133.77,Withdrawal,Groceries,Stop & Shop,Wire Transfer,Completed
14,104665.0,2023-11-12,Checking,Philadelphia,Pennsylvania,1958.72,Transfer,Rent,Rent Payment,Cash,Completed
15,104554.0,2026-07-03,Credit Card,Boston,Massachusetts,408.93,Payment,Entertainment,AMC Theatres,Debit Card,Completed
16,103646.0,2024-11-12,Credit Card,Philadelphia,Pennsylvania,1381.04,Withdrawal,Groceries,Costco,Cash,Completed
17,100837.0,2023-08-28,Money Market,Hartford,Connecticut,1783.21,Payment,Income,Payroll Deposit,Debit Card,Completed
18,105385.0,2022-05-08,Credit Card,Newark,New Jersey,2487.15,Transfer,Transportation,Uber,Wire Transfer,Pending
19,101831.0,2024-10-17,Money Market,Albany,New York,562.04,Deposit,Groceries,Whole Foods,ACH,Completed
20,107600.0,2023-10-12,Money Market,Albany,New York,1954.44,Deposit,Dining,Starbucks,Check,Completed
21,100828.0,24/04/2022,Savings,New York,New York,1624.61,Fee,Fees,Late Fee,ACH,Completed
22,102560.0,2026-07-27,Money Market,Brooklyn,New York,430.51,Payment,Dining,Starbucks,Check,Completed
23,102686.0,2024-06-25,Money Market,Jersey City,New Jersey,842.49,Payment,Entertainment,Hulu,Check,Completed
24,100504.0,2026-02-03,Checking,Boston,Massachusetts,1531.07,Fee,Shopping,Best Buy,Debit Card,Completed
25,104092.0,2023-03-23,Checking,Trenton,New Jersey,647.30,Withdrawal,Transportation,Shell Gas Station,ACH,Completed
26,106340.0,2024-02-19,Money Market,Trenton,New Jersey,118.50,Deposit,Dining,Chipotle,Credit Card,Completed
27,105305.0,2024-10-06,Checking,Boston,Massachusetts,821.76,Payment,Entertainment,Steam,NaN,Completed
28,108240.0,2026-04-05,Money Market,Philadelphia,Pennsylvania,1601.03,Payment,Entertainment,Netflix,Check,Completed
29,100840.0,2022-05-09,Credit Card,Trenton,New Jersey,219.92,Withdrawal,Dining,Chipotle,ACH,Completed
30,108931.0,2024-11-12,Savings,Philadelphia,Pennsylvania,685.09,Payment,Shopping,Walmart,Wire Transfer,Completed
31,101832.0,2023-02-17,Money Market,Albany,New York,326.64,Withdrawal,Healthcare,Walgreens,ACH,Pending
32,105588.0,2022-04-20,Checking,Albany,New York,2788.39,Payment,Insurance,State Farm,ACH,Completed
33,101703.0,2024-09-21,Credit Card,New York,New York,2600.40,Payment,Shopping,Target,Debit Card,Completed
34,102630.0,2022-12-17,Credit Card,Philadelphia,Pennsylvania,2251.77,Fee,Fees,ATM Fee,Credit Card,Completed
35,108467.0,2023-02-27,Money Market,Albany,New York,964.90,Withdrawal,Healthcare,Copay - Dr. Visit,Wire Transfer,Completed
36,107547.0,2026-02-24,Credit Card,Trenton,New Jersey,2840.57,Payment,Transfers,Zelle Transfer,Cash,Completed
37,100499.0,2026-06-05,Money Market,Albany,New York,393.53,Payment,Insurance,Geico,Wire Transfer,Completed
38,102987.0,2025-06-18,Money Market,Stamford,Connecticut,2529.06,Deposit,Groceries,Trader Joe's,ACH,Completed
39,101550.0,2026-08-20,Checking,Philadelphia,Pennsylvania,303.04,Withdrawal,Shopping,Best Buy,Cash,Completed
40,106086.0,2022-11-30,Credit Card,Brooklyn,New York,3176.65,Withdrawal,Utilities,Con Edison,Debit Card,Completed
41,104231.0,2025-01-16,Savings,Hartford,Connecticut,1830.82,Payment,Salary,Payroll Deposit,Check,Completed
42,104254.0,2022-07-21,Checking,Newark,New Jersey,885.49,Withdrawal,Healthcare,CVS Pharmacy,Cash,Completed
43,108948.0,2024-06-13,Savings,Boston,Massachusetts,1878.02,Withdrawal,Fees,ATM Fee,Check,Completed
44,110053.0,2025-11-03,Credit Card,Philadelphia,Pennsylvania,2591.34,Deposit,Transfers,Venmo,Check,Completed
45,105509.0,21/04/2025,Savings,White Plains,New York,1492.32,Deposit,Entertainment,Netflix,Debit Card,Completed
46,108451.0,2026-04-11,Money Market,Brooklyn,New York,2817.36,Transfer,Utilities,Verizon Fios,ACH,Pending
47,109805.0,2025-07-29,Money Market,Albany,New York,3055.50,Transfer,Healthcare,Copay - Dr. Visit,Check,Completed
48,103004.0,2024-04-06,Savings,New York,New York,1219.92,Transfer,Healthcare,NaN,Cash,Completed
49,103330.0,2025-07-22,Savings,Trenton,New Jersey,2618.76,Fee,Fees,ATM Fee,Credit Card,Completed

In [12]:
accounts['transaction_date']=pd.to_datetime(accounts['transaction_date'],errors='coerce')
accounts['transaction_date'].head(50)

0    2025-12-01
1    2025-02-27
2    2024-05-31
3    2022-07-20
4    2023-11-24
5    2025-09-03
6    2025-05-17
7    2025-09-06
8    2022-05-06
9    2025-04-27
10   2025-11-07
11   2024-02-24
12   2024-08-18
13   2023-06-19
14   2023-11-12
15   2026-07-03
16   2024-11-12
17   2023-08-28
18   2022-05-08
19   2024-10-17
20   2023-10-12
21   2022-04-24
22   2026-07-27
23   2024-06-25
24   2026-02-03
25   2023-03-23
26   2024-02-19
27   2024-10-06
28   2026-04-05
29   2022-05-09
30   2024-11-12
31   2023-02-17
32   2022-04-20
33   2024-09-21
34   2022-12-17
35   2023-02-27
36   2026-02-24
37   2026-06-05
38   2025-06-18
39   2026-08-20
40   2022-11-30
41   2025-01-16
42   2022-07-21
43   2024-06-13
44   2025-11-03
45   2025-04-21
46   2026-04-11
47   2025-07-29
48   2024-04-06
49   2025-07-22
Name: transaction_date, dtype: datetime64[ns]

In [13]:
accounts=accounts.set_index('transaction_id')
accounts.head(50)

,transaction_date,account_type,branch_city,branch_state,amount,transaction_type,category,merchant,payment_method,status
transaction_id,,,,,,,,,,
106499.0,2025-12-01,Money Market,Albany,New York,2282.09,Payment,Transportation,EZ-Pass,Wire Transfer,Completed
101635.0,2025-02-27,Savings,Philadelphia,Pennsylvania,431.86,Transfer,Transportation,Lyft,NaN,Pending
102938.0,2024-05-31,Checking,Stamford,Connecticut,277.69,Transfer,Shopping,Amazon,Cash,Completed
110478.0,2022-07-20,Credit Card,New York,New York,2999.37,Transfer,Shopping,Target,Cash,Completed
100906.0,2023-11-24,Savings,Hartford,Connecticut,1087.05,Withdrawal,Fees,Late Fee,Cash,Completed
104027.0,2025-09-03,Money Market,Jersey City,New Jersey,102.75,Withdrawal,Utilities,PSEG,Debit Card,Pending
105516.0,2025-05-17,Credit Card,New York,New York,1605.73,Fee,Rent,Rent Payment,Cash,Completed
108794.0,2025-09-06,Credit Card,Newark,New Jersey,486.99,Deposit,Fees,Late Fee,Debit Card,Completed
107911.0,2022-05-06,Checking,Philadelphia,Pennsylvania,1844.79,Payment,Fees,Late Fee,Cash,Completed
105279.0,2025-04-27,Money Market,Hicksville,New York,2495.04,Withdrawal,Utilities,National Grid,Cash,Completed
108373.0,2025-11-07,Credit Card,Boston,Massachusetts,3060.68,Deposit,Groceries,Stop & Shop,Wire Transfer,Completed
102618.0,2024-02-24,Credit Card,Trenton,New Jersey,2562.89,Transfer,Entertainment,Hulu,Cash,Completed
105580.0,2024-08-18,Checking,Albany,New York,1344.25,Withdrawal,Transportation,EZ-Pass,Check,Completed
101092.0,2023-06-19,Savings,Trenton,New Jersey,133.77,Withdrawal,Groceries,Stop & Shop,Wire Transfer,Completed
104665.0,2023-11-12,Checking,Philadelphia,Pennsylvania,1958.72,Transfer,Rent,Rent Payment,Cash,Completed
104554.0,2026-07-03,Credit Card,Boston,Massachusetts,408.93,Payment,Entertainment,AMC Theatres,Debit Card,Completed
103646.0,2024-11-12,Credit Card,Philadelphia,Pennsylvania,1381.04,Withdrawal,Groceries,Costco,Cash,Completed
100837.0,2023-08-28,Money Market,Hartford,Connecticut,1783.21,Payment,Income,Payroll Deposit,Debit Card,Completed
105385.0,2022-05-08,Credit Card,Newark,New Jersey,2487.15,Transfer,Transportation,Uber,Wire Transfer,Pending
101831.0,2024-10-17,Money Market,Albany,New York,562.04,Deposit,Groceries,Whole Foods,ACH,Completed
107600.0,2023-10-12,Money Market,Albany,New York,1954.44,Deposit,Dining,Starbucks,Check,Completed
100828.0,2022-04-24,Savings,New York,New York,1624.61,Fee,Fees,Late Fee,ACH,Completed
102560.0,2026-07-27,Money Market,Brooklyn,New York,430.51,Payment,Dining,Starbucks,Check,Completed
102686.0,2024-06-25,Money Market,Jersey City,New Jersey,842.49,Payment,Entertainment,Hulu,Check,Completed
100504.0,2026-02-03,Checking,Boston,Massachusetts,1531.07,Fee,Shopping,Best Buy,Debit Card,Completed
104092.0,2023-03-23,Checking,Trenton,New Jersey,647.30,Withdrawal,Transportation,Shell Gas Station,ACH,Completed
106340.0,2024-02-19,Money Market,Trenton,New Jersey,118.50,Deposit,Dining,Chipotle,Credit Card,Completed
105305.0,2024-10-06,Checking,Boston,Massachusetts,821.76,Payment,Entertainment,Steam,NaN,Completed
108240.0,2026-04-05,Money Market,Philadelphia,Pennsylvania,1601.03,Payment,Entertainment,Netflix,Check,Completed
100840.0,2022-05-09,Credit Card,Trenton,New Jersey,219.92,Withdrawal,Dining,Chipotle,ACH,Completed
108931.0,2024-11-12,Savings,Philadelphia,Pennsylvania,685.09,Payment,Shopping,Walmart,Wire Transfer,Completed
101832.0,2023-02-17,Money Market,Albany,New York,326.64,Withdrawal,Healthcare,Walgreens,ACH,Pending
105588.0,2022-04-20,Checking,Albany,New York,2788.39,Payment,Insurance,State Farm,ACH,Completed
101703.0,2024-09-21,Credit Card,New York,New York,2600.40,Payment,Shopping,Target,Debit Card,Completed
102630.0,2022-12-17,Credit Card,Philadelphia,Pennsylvania,2251.77,Fee,Fees,ATM Fee,Credit Card,Completed
108467.0,2023-02-27,Money Market,Albany,New York,964.90,Withdrawal,Healthcare,Copay - Dr. Visit,Wire Transfer,Completed
107547.0,2026-02-24,Credit Card,Trenton,New Jersey,2840.57,Payment,Transfers,Zelle Transfer,Cash,Completed
100499.0,2026-06-05,Money Market,Albany,New York,393.53,Payment,Insurance,Geico,Wire Transfer,Completed
102987.0,2025-06-18,Money Market,Stamford,Connecticut,2529.06,Deposit,Groceries,Trader Joe's,ACH,Completed
101550.0,2026-08-20,Checking,Philadelphia,Pennsylvania,303.04,Withdrawal,Shopping,Best Buy,Cash,Completed
106086.0,2022-11-30,Credit Card,Brooklyn,New York,3176.65,Withdrawal,Utilities,Con Edison,Debit Card,Completed
104231.0,2025-01-16,Savings,Hartford,Connecticut,1830.82,Payment,Salary,Payroll Deposit,Check,Completed
104254.0,2022-07-21,Checking,Newark,New Jersey,885.49,Withdrawal,Healthcare,CVS Pharmacy,Cash,Completed
108948.0,2024-06-13,Savings,Boston,Massachusetts,1878.02,Withdrawal,Fees,ATM Fee,Check,Completed
110053.0,2025-11-03,Credit Card,Philadelphia,Pennsylvania,2591.34,Deposit,Transfers,Venmo,Check,Completed
105509.0,2025-04-21,Savings,White Plains,New York,1492.32,Deposit,Entertainment,Netflix,Debit Card,Completed
108451.0,2026-04-11,Money Market,Brooklyn,New York,2817.36,Transfer,Utilities,Verizon Fios,ACH,Pending
109805.0,2025-07-29,Money Market,Albany,New York,3055.50,Transfer,Healthcare,Copay - Dr. Visit,Check,Completed
103004.0,2024-04-06,Savings,New York,New York,1219.92,Transfer,Healthcare,NaN,Cash,Completed
103330.0,2025-07-22,Savings,Trenton,New Jersey,2618.76,Fee,Fees,ATM Fee,Credit Card,Completed

In [14]:
corrected_dates=accounts.to_csv('~/Desktop/corrected_dates.csv')